// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarriorsGuild.DataAccess;

namespace WarriorsGuild.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210609142200_Update cross models")]
    partial class Updatecrossmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.Cross", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuideUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImageUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Crosses");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecalledByWarriorTs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedTs")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CrossId");

                    b.HasIndex("DayId");

                    b.ToTable("CrossApprovals");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossDay", b =>
                {
                    b.Property<Guid>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Passage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DayId");

                    b.ToTable("CrossDays");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossDayAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CrossDayAnswers");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CrossId");

                    b.ToTable("CrossQuestions");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.PinnedCross", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CrossId");

                    b.HasIndex("CrossId");

                    b.ToTable("PinnedCrosses");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.BillingAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdditionalGuardians")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalWarriors")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Cancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextPaymentDue")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid?>("PriceOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PriceOptionId");

                    b.ToTable("BillingAgreements");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.Stripe.StripeWebhookMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LiveMode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeEvent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StripeWebhookMessages");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.SubscriptionBillingAgreement", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubscriptionId", "BillingAgreementId");

                    b.HasIndex("BillingAgreementId");

                    b.ToTable("SubscriptionBillingAgreements");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPayingParty")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Revised")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RevisedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SubscriptionId", "BillingAgreementId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuideUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImageUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.RankRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionToComplete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireAttachment")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireCross")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireRing")
                        .HasColumnType("bit");

                    b.Property<int?>("RequiredCrossCount")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredRingCount")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredRingType")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("RankRequirements");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.Status.RankApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("int");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RecalledByWarriorTs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedTs")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("RankApprovals");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.Status.RankStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("GuardianCompleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RankRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RecalledByWarriorTs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedTs")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WarriorCompleted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("RankStatuses");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.PinnedRing", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RingId");

                    b.HasIndex("RingId");

                    b.ToTable("PinnedRings");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.Ring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuideUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImageUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rings");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.RingApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RecalledByWarriorTs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedTs")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RingId");

                    b.ToTable("RingApprovals");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.RingRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionToComplete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("RequireAttachment")
                        .HasColumnType("bit");

                    b.Property<Guid>("RingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RingId");

                    b.ToTable("RingRequirements");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.Status.RingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("GuardianCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RecalledByWarriorTs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedTs")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RingRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WarriorCompleted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RingId");

                    b.ToTable("RingStatuses");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.CrossAnswer", b =>
                {
                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrossQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrossId", "CrossQuestionId", "UserId");

                    b.ToTable("CrossAnswers");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.InvitedEmailAddress", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmailAddress");

                    b.ToTable("InvitedEmailAddresses");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.ProofOfCompletionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId", "UserId");

                    b.ToTable("ProofOfCompletionAttachments");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.RankStatusCompletedCross", b =>
                {
                    b.Property<Guid>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RankRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("RankId", "RankRequirementId", "UserId", "CrossId");

                    b.HasIndex("CrossId");

                    b.ToTable("RankStatusCrosses");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.RankStatusCompletedRing", b =>
                {
                    b.Property<Guid>("RankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RankRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("RankId", "RankRequirementId", "UserId", "RingId");

                    b.HasIndex("RingId");

                    b.ToTable("RankStatusRings");
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.SingleUseFileDownloadKey", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.ToTable("SingleUseFileDownloadKey");
                });

            modelBuilder.Entity("WarriorsGuild.Models.Account.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("AvatarUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FavoriteMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteVerse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestingFact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShirtSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("AvatarUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WarriorsGuild.Models.Account.AvatarDetail", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AvatarDetail");
                });

            modelBuilder.Entity("WarriorsGuild.Models.MailingListEntry", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("FreeReportSent")
                        .HasColumnType("bit");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("bit");

                    b.HasKey("EmailAddress");

                    b.ToTable("MailingList");
                });

            modelBuilder.Entity("WarriorsGuild.Providers.Payments.Models.AddOnPriceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuardians")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWarriors")
                        .HasColumnType("int");

                    b.Property<bool>("Show")
                        .HasColumnType("bit");

                    b.Property<string>("StripePlanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrialPeriodLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AddOnPriceOptions");
                });

            modelBuilder.Entity("WarriorsGuild.Providers.Payments.Models.PriceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdditionalGuardianPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdditionalWarriorPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("HasTrialPeriod")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuardians")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWarriors")
                        .HasColumnType("int");

                    b.Property<decimal>("SetupFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Show")
                        .HasColumnType("bit");

                    b.Property<string>("StripePlanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrialPeriodLength")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Voided")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalGuardianPlanId");

                    b.HasIndex("AdditionalWarriorPlanId");

                    b.HasIndex("Id", "ModifiedDate");

                    b.ToTable("PriceOptions");
                });

            modelBuilder.Entity("WarriorsGuild.Providers.Payments.Models.PriceOptionPerk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<Guid>("PriceOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriceOptionId");

                    b.ToTable("PriceOptionPerks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WarriorsGuild.Models.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WarriorsGuild.Models.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarriorsGuild.Models.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WarriorsGuild.Models.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossApproval", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Crosses.Models.Cross", "Cross")
                        .WithMany()
                        .HasForeignKey("CrossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarriorsGuild.Areas.Crosses.Models.CrossDay", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.CrossQuestion", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Crosses.Models.Cross", null)
                        .WithMany("Questions")
                        .HasForeignKey("CrossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Crosses.Models.PinnedCross", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Crosses.Models.Cross", "Cross")
                        .WithMany()
                        .HasForeignKey("CrossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.BillingAgreement", b =>
                {
                    b.HasOne("WarriorsGuild.Providers.Payments.Models.PriceOption", "PriceOption")
                        .WithMany()
                        .HasForeignKey("PriceOptionId");
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Payments.Models.SubscriptionBillingAgreement", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Payments.Models.BillingAgreement", "BillingAgreement")
                        .WithMany()
                        .HasForeignKey("BillingAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.RankRequirement", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Ranks.Models.Rank", null)
                        .WithMany("Requirements")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.Status.RankApproval", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Ranks.Models.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Ranks.Models.Status.RankStatus", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Ranks.Models.Rank", null)
                        .WithMany("Statuses")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.PinnedRing", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Rings.Models.Ring", "Ring")
                        .WithMany()
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.RingApproval", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Rings.Models.Ring", "Ring")
                        .WithMany()
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.RingRequirement", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Rings.Models.Ring", null)
                        .WithMany("Requirements")
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Areas.Rings.Models.Status.RingStatus", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Rings.Models.Ring", null)
                        .WithMany("Statuses")
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.RankStatusCompletedCross", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Crosses.Models.Cross", "Cross")
                        .WithMany()
                        .HasForeignKey("CrossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.DataAccess.Models.RankStatusCompletedRing", b =>
                {
                    b.HasOne("WarriorsGuild.Areas.Rings.Models.Ring", "Ring")
                        .WithMany()
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarriorsGuild.Models.Account.ApplicationUser", b =>
                {
                    b.HasOne("WarriorsGuild.Models.Account.ApplicationUser", null)
                        .WithMany("ChildUsers")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("WarriorsGuild.Models.Account.AvatarDetail", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarUserId");
                });

            modelBuilder.Entity("WarriorsGuild.Providers.Payments.Models.PriceOption", b =>
                {
                    b.HasOne("WarriorsGuild.Providers.Payments.Models.AddOnPriceOption", "AdditionalGuardianPlan")
                        .WithMany()
                        .HasForeignKey("AdditionalGuardianPlanId");

                    b.HasOne("WarriorsGuild.Providers.Payments.Models.AddOnPriceOption", "AdditionalWarriorPlan")
                        .WithMany()
                        .HasForeignKey("AdditionalWarriorPlanId");
                });

            modelBuilder.Entity("WarriorsGuild.Providers.Payments.Models.PriceOptionPerk", b =>
                {
                    b.HasOne("WarriorsGuild.Providers.Payments.Models.PriceOption", null)
                        .WithMany("Perks")
                        .HasForeignKey("PriceOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
